"""Constants for the Watergate integration."""

DOMAIN = "watergate"

SONIC_NAME = "sonic_name"
SONIC_ADDRESS = "sonic_address"

MANUFACTURER = "Watergate AI"

COORDINATOR = "watergate-coordinator"
API = "api-client"

VALVE_SENSOR_NAME = "Valve"
WIFI_CONNECTION_SENSOR_NAME = "Wifi connection"
MQTT_CONNECTION_SENSOR_NAME = "MQTT connection"
UPTIME_SENSOR_NAME = "Uptime"
UPTIME_SENSOR_NAME = "Uptime"
POWER_SUPPLY_SENSOR_NAME = "Power supply"
WATER_FLOWING_SENSOR_NAME = "Water flowing"
PRESSURE_SENSOR_NAME = "Water pressure"
TEMPERATURE_SENSOR_NAME = "Water temperature"
FLOW_SENSOR_NAME = "Water flow rate"
IP_SENSOR_NAME = "IP address"
GATEWAY_SENSOR_NAME = "Gateway address"
SUBNET_SENSOR_NAME = "Subnet"
SSID_SENSOR_NAME = "SSID"
RSSI_SENSOR_NAME = "RSSI"
WIFI_UPTIME_SENSOR_NAME = "WIFI Uptime"
MQTT_UPTIME_SENSOR_NAME = "MQTT Uptime"
SHUT_OFF_SENSOR_NAME = "Auto Shut off"
SHUT_OFF_VOLUME_SENSOR_NAME = "Auto Shut off volume"
SHUT_OFF_DURATION_SENSOR_NAME = "Auto Shut off duration"
SHUT_OFF_EVENT_SENSOR_NAME = "Last Auto Shut off event"
WATER_METER_VOLUME_SENSOR_NAME = "Water meter volume"
WATER_METER_DURATION_SENSOR_NAME = "Water meter duration"


VALVE_ENTITY_NAME = "valve"
WIFI_CONNECTION_ENTITY_NAME = "wifi_status"
MQTT_CONNECTION_ENTITY_NAME = "mqtt_status"
UPTIME_ENTITY_NAME = "uptime"
POWER_SUPPLY_ENTITY_NAME = "power_supply"
WATER_FLOWING_ENTITY_NAME = "water_flowing"
PRESSURE_ENTITY_NAME = "water_pressure"
TEMPERATURE_ENTITY_NAME = "water_temperature"
FLOW_ENTITY_NAME = "water_flow_rate"
IP_ENTITY_NAME = "ip"
GATEWAY_ENTITY_NAME = "gateway"
SUBNET_ENTITY_NAME = "subnet"
SSID_ENTITY_NAME = "ssid"
RSSI_ENTITY_NAME = "rssi"
WIFI_UPTIME_ENTITY_NAME = "wifi_uptime"
MQTT_UPTIME_ENTITY_NAME = "mqtt_uptime"
SHUT_OFF_ENTITY_NAME = "auto_shut_off"
SHUT_OFF_VOLUME_ENTITY_NAME = "auto_shut_off_volume"
SHUT_OFF_DURATION_ENTITY_NAME = "auto_shut_off_duration"
SHUT_OFF_EVENT_ENTITY_NAME = "auto_shut_off_event"
WATER_METER_VOLUME_ENTITY_NAME = "water_meter_volume"
WATER_METER_DURATION_ENTITY_NAME = "water_meter_duration"

ASO_EVENT_TYPE_ATRIBUTE = "type"
ASO_EVENT_VOLUME_ATRIBUTE = "volume"
ASO_EVENT_DURATION_ATRIBUTE = "duration"

WEBHOOK_ASO_REPORT_TYPE = "auto-shut-off-report"
WEBHOOK_TELEMETRY_TYPE = "telemetry"
WEBHOOK_VALVE_TYPE = "valve"
WEBHOOK_WIFI_CHANGED_TYPE = "wifi-changed"
WEBHOOK_POWER_SUPPLY_CHANGED_TYPE = "power-supply-changed"
